type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  code: 
    type: string
  description: 
    type: string
  version: 
    type: string
  enabled: 
    type: boolean
  author: 
    type: [ string, 'null' ]
  websiteUrl: 
    type: [ string, 'null' ]
  sourceCodeLocationUrl: 
    type: [ string, 'null' ]
  issueTrackerUrl: 
    type: [ string, 'null' ]
  valid: 
    type: boolean
  hasValidUpdate: 
    type: boolean
  status: 
    type: string
  statusMessage: 
    type: [ string, 'null' ]
  providers: 
    type: array
    items: 
      type: object
      properties: 
        name: 
          type: string
        type: 
          type: string
  config: 
    type: object
  optionTypes: 
    type: array
    items: 
      $ref: optionType.yaml
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
